version: '3.9'
services:
  bot:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TOKEN: ${TOKEN}
      YOUTUBE_EMAIL: ${YOUTUBE_EMAIL}
      YOUTUBE_PASSWORD: ${YOUTUBE_PASSWORD}
    env_file:
      - .env
    networks:
      - default