version: '3.9'
services:
  postgres:
    container_name: discord-db
    build:
      context: .
      dockerfile: dockerfile/dbDockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: discord
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./.postgresql:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge