spring:
  main:
    web-application-type: NONE
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/discord
    username: ${db_user:postgres}
    password: ${db_password:changeme}
token: token
youtube:
  email: ''
  password: ''
